const numberOfDrinksSearched = 5;
var searchedDrinksArray = [];

//called at the end of the search functions do display the info
function displaySearchedInformation(drinkName, ingrediantList, drinkRecipe, drinkThumbnailSrc){
    //TODO create display function
}

//get a random cocktail
function getRandomDrinkRecipe(){
    var urlPath = "https://www.thecocktaildb.com/api/json/v1/1/random.php";

    $.ajax({
        url: urlPath,
        method: "GET"
    }).then(function(response){
        //the info about the actual drink
        var drinkInfo = response.drinks[0];

        //the name of the drink
        var drinkName = drinkInfo.strDrink;
        
        //the list will be generated by the following for loop
        var ingrediantList = [];
        
        //loops throught the ingredients list
        for(var i = 1; i <= 15; i++){
            //they didn't put the ingredients in an array, so this is how I have to loop through them 
            var ingrediant = "strIngredient" + i;
            var amount = "strMeasure" + i;

            //and here I thought this method of accessing an object's properties would never come in handy
            //turns out it's great when the name of that property can be generated in the form of a string!
            if(drinkInfo[ingrediant] != null){
                if(drinkInfo[amount] != null)
                {
                    var newIngredient = drinkInfo[ingrediant] + ": " + drinkInfo[amount];
                    ingrediantList.push(newIngredient);
                }
                else 
                {
                    var newIngredient = drinkInfo[ingrediant];
                    ingrediantList.push(newIngredient);
                }
                //ends the loop if its gone through all the ingredients
            }else{
                break;
            }
        }

        //the recipe of the drink
        var drinkRecipe = drinkInfo.strInstructions;

        //the url to an image of the drink. Be sure to add it to the src of the acompanying image
        var drinkThumbnailSrc = drinkInfo.strDrinkThumb;

        //TODO create script that displays this info in the html
        console.log(drinkName);
        $.each(ingrediantList, function(i, index){
            console.log(index);
        });
        console.log(drinkRecipe);
        console.log(drinkThumbnailSrc);
    });
}

//NOT accessed by user, is used by searchCocktailByIngrediant
function searchByID(id){
    var urlPath = "https://www.thecocktaildb.com/api/json/v1/1/lookup.php?i=" + id;

    $.ajax({
        url: urlPath,
        method: "GET"
    }).then(function(response){
        //check to make sure the search term returned a recipe
        //the rest of the code related to retrieving info from the response goes in here
        if(response.drinks != null)
        {
            var drinkInfo = response.drinks[0];

            //the name of the drink
            var drinkName = drinkInfo.strDrink;
            
            //the list will be generated by the following for loop
            var ingrediantList = [];
            
            //loops throught the ingredients list
            for(var i = 1; i <= 15; i++){
                //they didn't put the ingredients in an array, so this is how I have to loop through them 
                var ingrediant = "strIngredient" + i;
                var amount = "strMeasure" + i;

                //and here I thought this method of accessing an object's properties would never come in handy
                //turns out it's great when the name of that property can be generated in the form of a string!
                if(drinkInfo[ingrediant] != null){
                    if(drinkInfo[amount] != null)
                    {
                        var newIngredient = drinkInfo[ingrediant] + ": " + drinkInfo[amount];
                        ingrediantList.push(newIngredient);
                    }
                    else 
                    {
                        var newIngredient = drinkInfo[ingrediant];
                        ingrediantList.push(newIngredient);
                    }
                    //ends the loop if its gone through all the ingredients
                }else{
                    break;
                }
            }

            //the recipe of the drink
            var drinkRecipe = drinkInfo.strInstructions;

            //the url to an image of the drink. Be sure to add it to the src of the acompanying image
            var drinkThumbnailSrc = drinkInfo.strDrinkThumb;

            //TODO create script that displays this info in the html
            console.log(drinkName);
            $.each(ingrediantList, function(i, index){
                console.log(index);
            });
            console.log(drinkRecipe);
            console.log(drinkThumbnailSrc);
        }
        else
        {
            //TODO let the user know when the search failed
            console.log("No Recipes Found")
        }
    });
}

//search cocktail by name
function searchCocktailByName(name){
    var urlPath = "https://www.thecocktaildb.com/api/json/v1/1/search.php?s=" + name;

    $.ajax({
        url: urlPath,
        method: "GET"
    }).then(function(response){
        //check to make sure the search term returned a recipe
        //the rest of the code related to retrieving info from the response goes in here
        if(response.drinks != null)
        {
            var drinkInfo = response.drinks[0];

            //the name of the drink
            var drinkName = drinkInfo.strDrink;
            
            //the list will be generated by the following for loop
            var ingrediantList = [];
            
            //loops throught the ingredients list
            for(var i = 1; i <= 15; i++){
                //they didn't put the ingredients in an array, so this is how I have to loop through them 
                var ingrediant = "strIngredient" + i;
                var amount = "strMeasure" + i;

                //and here I thought this method of accessing an object's properties would never come in handy
                //turns out it's great when the name of that property can be generated in the form of a string!
                if(drinkInfo[ingrediant] != null){
                    if(drinkInfo[amount] != null)
                    {
                        var newIngredient = drinkInfo[ingrediant] + ": " + drinkInfo[amount];
                        ingrediantList.push(newIngredient);
                    }
                    else 
                    {
                        var newIngredient = drinkInfo[ingrediant];
                        ingrediantList.push(newIngredient);
                    }
                    //ends the loop if its gone through all the ingredients
                }else{
                    break;
                }
            }

            //the recipe of the drink
            var drinkRecipe = drinkInfo.strInstructions;

            //the url to an image of the drink. Be sure to add it to the src of the acompanying image
            var drinkThumbnailSrc = drinkInfo.strDrinkThumb;

            //TODO create script that displays this info in the html
            console.log(drinkName);
            $.each(ingrediantList, function(i, index){
                console.log(index);
            });
            console.log(drinkRecipe);
            console.log(drinkThumbnailSrc);
        }
        else
        {
            //TODO let the user know when the search failed
            console.log("No Recipes Found")
        }
    });
}

//searchCocktailByName("eudghsliugfsli");

//getRandomDrinkRecipe();

function pickRandomFromArray(array, amount){
    var inputArray = array;
    searchedDrinksArray = [];
    for(var i = 0; i < amount; i++){
        var randomNumber = Math.floor(Math.random() * inputArray.length);
        searchedDrinksArray.push(inputArray.splice(randomNumber, 1))
    }
}

var urlPath = "https://www.thecocktaildb.com/api/json/v1/1/filter.php?i=" + "vodka";

$.ajax({
    url: urlPath,
    method: "GET"
}).then(function(response){
    console.log(response);
    //make sure it actually got a response
    if(response != ""){
        pickRandomFromArray(response.drinks, numberOfDrinksSearched);

        $.each(searchedDrinksArray, function(i, value){
            searchByID(value[0].idDrink);
            // console.log(value);
            // var drinkInfo = value[0];

            // //the name of the drink
            // var drinkName = drinkInfo.strDrink;
            
            // //the list will be generated by the following for loop
            // var ingrediantList = [];
            
            // //loops throught the ingredients list
            // for(var i = 1; i <= 15; i++){
            //     //they didn't put the ingredients in an array, so this is how I have to loop through them 
            //     var ingrediant = "strIngredient" + i;
            //     var amount = "strMeasure" + i;

            //     //and here I thought this method of accessing an object's properties would never come in handy
            //     //turns out it's great when the name of that property can be generated in the form of a string!
            //     if(drinkInfo[ingrediant] != null){
            //         if(drinkInfo[amount] != null)
            //         {
            //             var newIngredient = drinkInfo[ingrediant] + ": " + drinkInfo[amount];
            //             ingrediantList.push(newIngredient);
            //         }
            //         else 
            //         {
            //             var newIngredient = drinkInfo[ingrediant];
            //             ingrediantList.push(newIngredient);
            //         }
            //         //ends the loop if its gone through all the ingredients
            //     }else{
            //         break;
            //     }
            // }

            // //the recipe of the drink
            // var drinkRecipe = drinkInfo.strInstructions;

            // //the url to an image of the drink. Be sure to add it to the src of the acompanying image
            // var drinkThumbnailSrc = drinkInfo.strDrinkThumb;

            // //TODO create script that displays this info in the html
            // console.log(drinkName);
            // $.each(ingrediantList, function(i, index){
            //     console.log(index);
            // });
            // console.log(drinkRecipe);
            // console.log(drinkThumbnailSrc);
        })
    }
});